- README.md
I did not want to hardcode the SCIP version so instruction cannot be copy-pasted
> Improve source installation instructions in README

- libecole/src/observation/nodebipartite.cpp
- libecole/src/scip/row.cpp
- libecole/src/scip/variable.cpp
I doublechecked if the bipartite node features in Ecole matched the old learn2branch node features. it wasn't the case, but after the following fixes I now get the same results.
```
> np.abs(new_col_feat - col_feat['values']).max()
2.9450719307710926e-08
> np.abs(new_row_feat - row_feat['values'][new_to_old, :]).max()
7.080813868576286e-08
```
Ideally, we would also add a unit test to make them match; however, this would require the developer to have a custom version of PySCIPOpt I think? I don't really need how to make this light.
In addition, this is my first pull request. Is there tools I need to run on my PR?
> Make bipartite nodes compatible with learn2branch

- libecole/include/ecole/observation/nodebipartite.hpp
- libecole/src/observation/nodebipartite.cpp
- python/src/ecole/__init__.py.in
- python/src/ecole/core/observation.cpp
- python/tests/test_observation.py
This pull request proposes to change names of the node bipartite observation features as:
- `obs.row_feat` -> `obs.row_features`
- `obs.col_feat` -> `obs.column_features`
- `obs.matrix` -> `obs.edge_features`
Also, right now we must manually import every submodule we wish to use:
```
import ecole.environment
env = ecole.environment.Branching()
```
This pull request proposes to bring back submodule imports, so that
```
import ecole
env = ecole.environment.Branching()
```
works again. (It used to be the case.)
> Node bipartite names and submodule imports

- docs/reference/rewards.rst
- libecole/CMakeLists.txt
- libecole/include/ecole/reward/nnodes.hpp
- libecole/src/reward/nnodes.cpp
- libecole/tests/CMakeLists.txt
- libecole/tests/src/reward/test-lpiterations.cpp
- libecole/tests/src/reward/test-nnodes.cpp
- python/src/ecole/core/reward.cpp
- python/tests/test_reward.py
NNodes reward: computes the difference in the total number of nodes between the previous and the current state. This is properly defined even considering B&B restarts, as the total number of B&B nodes from all restarts are accounted for.
> Implementation and test of the new NNodes reward function

- docs/conf.py.in
- docs/discussion/theory.rst
- docs/static/css/custom.css
This is a first draft, I tried to be clear and concise. Let me know what you think !
> Documentation: theory page

- libecole/CMakeLists.txt
- libecole/include/ecole/reward/solvingtime.hpp
- libecole/src/reward/solvingtime.cpp
- libecole/tests/src/reward/test-solvingtime.cpp
- python/src/ecole/core/reward.cpp
Implementation of solving time reward `ecole.reward.SolvingTime()`. Can take an optional boolean parameter `wall` to decide whether one wants to use wall time or process time (default).
I think it is worthwhile to explain a bit the design decisions. As we all know, timing is tricky. Here were goals that I tried to balance:
- One of the timing rewards should match what was used to report timings in the learn2branch paper (gold standard).
- If we offer several timing rewards, it should be possible for the user to run them all simultaneously on the same environment (e.g. to report both wall and process times).
It turns out that this is not easy to do. I think my implementation does a good job given those constraints, while trying to be as simple as possible. Here's how I ended up …
> Solvingtime

- libecole/CMakeLists.txt
- libecole/include/ecole/reward/solvingtime.hpp
- libecole/include/ecole/utility/chrono.hpp
- libecole/src/reward/solvingtime.cpp
- libecole/src/utility/chrono.cpp
- libecole/tests/CMakeLists.txt
- libecole/tests/src/utility/test-chrono.cpp
- python/src/ecole/core/reward.cpp
I am also needing to time CPU for benchmarking the observation functions so I made it into a `clock`.
I switched to `clock_gettime`, even though it is not standard as it has higher resolution (nano vs micro?).
`std::clock` is allegedly not giving CPU time on Windows anyways.
One question remains. What should be the unit of `SolvingTime`? Previously it was in miliseconds. In this PR, it is currently in nanoseconds.
While we may not need that much precision, there is also little need make the approximation to miliseconds earlier than necessary. It can easily be done using `SolvingTime() / 1e6`.
> Refactor solving time to use cpu_clock

- libecole/include/ecole/observation/nodebipartite.hpp
- libecole/src/observation/nodebipartite.cpp
- libecole/tests/src/observation/test-nodebipartite.cpp
- python/src/ecole/core/observation.cpp
This add a manual cache to `NodeBipartite` similar to _Gasse et al._ (2019).
The cache is only safe to use when not using cuts.
Future improvements would include:
- Automatically detect when we can activate the cache;
- Always enable the cache but detect when the cache is invalid within an episode (is it worth it);
- Have a dynamic per row / per col cache that can reuse previous computation even if the structure of the problem has changed.
> Add manual cache to NodeBipartite

- libecole/include/ecole/instance/capacitated-facility-location.hpp
- libecole/src/instance/capacitated-facility-location.cpp
- libecole/tests/src/instance/test-capacitated-facility-location.cpp
Three fixes:
1. the generator was imposing discrete servings by default (continuous_assignment = false);
2. instances were missing a global tightening constraint: the total demand must be satisfied;
3. the capacities were taking non-integer values, due to the scaling.
It looks like 1. was what was making the generated instances so difficult.
Addresses issue #141
> Bugfix: instance generator for capacitated facility location

- libecole/include/ecole/instance/combinatorial-auction.hpp
- libecole/include/ecole/instance/independent-set.hpp
Changes to the generators so that the defaults match the way instances were generated in the learn2branch paper (or at least, that they have reasonable difficulty.)
> Good instance generator defaults

- docs/reference/instances.rst
- libecole/CMakeLists.txt
- libecole/include/ecole/exception.hpp
- libecole/include/ecole/instance/abstract.hpp
- libecole/include/ecole/instance/capacitated-facility-location.hpp
- libecole/include/ecole/instance/combinatorial-auction.hpp
- libecole/include/ecole/instance/files.hpp
- libecole/include/ecole/instance/independent-set.hpp
- libecole/include/ecole/instance/set-cover.hpp
- libecole/include/ecole/scip/model.hpp
- libecole/src/instance/files.cpp
- libecole/src/scip/model.cpp
- libecole/tests/CMakeLists.txt
- libecole/tests/src/instance/test-files.cpp
- libecole/tests/src/instance/unit-tests.hpp
- libecole/tests/src/test-utility/tmp-folder.cpp
- libecole/tests/src/test-utility/tmp-folder.hpp
- python/src/ecole/core/core.cpp
- python/src/ecole/core/instance.cpp
- python/src/ecole/core/scip.cpp
- python/tests/conftest.py
- python/tests/test_instance.py
So far an instance loader that iterates over regular files (no glob/filter).
It  does not set any scip parameters.
@gasse @dchetelat It was a bit hard to design tests for it (because you need a local dataset...), so if you want to take it for a spin, make sure that everything is OK, that'd be great.
> Local files instance loader

- docs/reference/environments.rst
- libecole/CMakeLists.txt
- libecole/include/ecole/dynamics/branching-gub.hpp
- libecole/include/ecole/dynamics/branching.hpp
- libecole/include/ecole/environment/branching-gub.hpp
- libecole/include/ecole/scip/model.hpp
- libecole/include/ecole/scip/scimpl.hpp
- libecole/src/dynamics/branching-gub.cpp
- libecole/src/dynamics/branching.cpp
- libecole/src/scip/gub-branch.cpp
- libecole/src/scip/gub-branch.hpp
- libecole/src/scip/model.cpp
- libecole/src/scip/scimpl.cpp
- libecole/tests/CMakeLists.txt
- libecole/tests/src/dynamics/test-branching-gub.cpp
- libecole/tests/src/dynamics/test-branching.cpp
- libecole/tests/src/dynamics/test-configuring.cpp
- libecole/tests/src/dynamics/unit-tests.hpp
- libecole/tests/src/scip/test-model.cpp
- python/src/ecole/core/auto-class.hpp
- python/src/ecole/core/dynamics.cpp
- python/src/ecole/environment.py
- python/tests/test_dynamics.py
For integer variables `x_i` provided by the user, and their LP relaxation value `x_lp_i`,
- If `s := sum(x_lp_i)` is fractional, then branch on `sum(x_i) <= floor(s)` & `sum(x_i) >= ceil(s)`
- If `s := sum(x_lp_i)` is integer, then branch on `sum(x_i) <= s - 1` & `sum(x_i) == s` & `sum(x_i) >= s+ 1`
- When `n_vars == 0`, fail;
- Otherwise (including when `n_vars == 1`):
- Fail if any variable is continuous or fixed
- if `sum(x_lp_i)` is infinite, what then?
- if `sum(x_lp_i)` is integer, branch on three nodes
- else branch on two nodes
> Implement GUB branching

- docs/reference/environments.rst
- libecole/CMakeLists.txt
- libecole/include/ecole/dynamics/primalsearch.hpp
- libecole/include/ecole/environment/primalsearch.hpp
- libecole/include/ecole/scip/model.hpp
- libecole/include/ecole/scip/scimpl.hpp
- libecole/src/dynamics/branching-sum.cpp
- libecole/src/dynamics/branching.cpp
- libecole/src/dynamics/primalsearch.cpp
- libecole/src/scip/model.cpp
- libecole/src/scip/scimpl.cpp
- libecole/tests/CMakeLists.txt
- libecole/tests/src/conftest.cpp
- libecole/tests/src/dynamics/test-primalsearch.cpp
- libecole/tests/src/scip/test-model.cpp
- python/src/ecole/core/dynamics.cpp
- python/src/ecole/environment.py
- python/tests/test_dynamics.py
- python/tests/test_environment.py
The environment is implemented though a [primal heuristic plugin](https://www.scipopt.org/doc/html/HEUR.php). The environment deviates little from the behavior of a primal heuristic, except that it offers an option for the primal search to be called several times (users can be allowed several trials, i.e., several actions, at each node). Also, users have the option to provide only a partial solution, which SCIP will try to complete if possible by fixing the variables in the partial solution and then solving an LP.
> PrimalSearch environment

- python/src/ecole/environment.py
In-between two environment steps, the following happens:
- features are computed (observation function code)
- an action is taken (user code)
From the perspective of an agent, if it can control the observation computation process as well as the action decision process, then those two operations can actually be fused into one, where the observation function directly returns the action which is to be taken.
Consider the following scenario: I use a configuring environment with the solving time as a reward. I want to discard the initial reward, as I do not want to account for the time it takes to load the instance file into SCIP. With the code as it is now, this will also discard the time it takes to compute the initial observation. As such, if I drop the initial reward, smart users might …
> Extract reward before observation

- libecole/include/ecole/environment/environment.hpp
- python/src/ecole/environment.py
> Extract reward before observation (C++ and Python)

- libecole/CMakeLists.txt
- libecole/include/ecole/environment/environment.hpp
- python/src/ecole/environment.py
I think we should release this new version quickly, to fix the current bug in 0.7.1 where observations are extracted twice.
Changes:
- fmt is now built as a static library
- reward / observation extraction is now made in the proper order in both the C++ and Python Environment class
- bugfix: observations are not extracted twice any more in the Python Environment class
> Release 0.7.2

- docs/_static/css/custom.css
On mobile, the top bar color was still the original blue instead of orange.
> Fix doc nav bar color on mobile

- libecole/include/ecole/observation/nodebipartite.hpp
- libecole/include/ecole/tweak/range.hpp
- libecole/src/dynamics/branching.cpp
- libecole/src/observation/khalil-2016.cpp
- libecole/src/observation/nodebipartite.cpp
- libecole/src/observation/pseudocosts.cpp
- libecole/src/observation/strongbranchingscores.cpp
- libecole/tests/src/observation/test-khalil-2016.cpp
- libecole/tests/src/observation/test-nodebipartite.cpp
- libecole/tests/src/observation/test-pseudocosts.cpp
- python/src/ecole/core/observation.cpp
- python/tests/test_observation.py
Like the title says.
Fixes #200 .
For all observation functions that iterate over variables, **all** variables should be iterated in the order of `Model::variables` (possibly leaving unwanted variables with `nan`).
> Remove LP notions (cols/rows) from observations

- libecole/include/ecole/observation/strongbranchingscores.hpp
- python/src/ecole/core/observation.cpp
> Change strongbranching pseudo_candidate default

- cmake/DependenciesResolver.cmake
Wrong use of `return` inside a CMake macro (which is not a function).
> Fix wrong return from macro

- libecole/include/ecole/dynamics/branching.hpp
- libecole/src/dynamics/branching.cpp
- libecole/tests/src/dynamics/test-branching.cpp
- python/ecole/src/ecole/core/dynamics.cpp
The motivation is two folds:
-  Be able to benchmark with a control flow similar that the one used for branching, collecting intermediary information (also very useful for debugging);
- Train agents that can be uncertain and prefer SCIP policy. 
Default branching is performed by passing `None` as an action / branching variable to `env.step`.
Alternatively, I though one could give a token, like
```python
env.step(ecole.environment.default_action)
```
The advantage would be to avoid involuntary default branching (if users unknowingly get a `None` output in their policy).
> Allow defaut SCIP in branching environment
