README.md
Previous description was a bit misleading IMO. ECOLE is not aimed at solving CO tasks (max ind. sets, knapsack etc.), but rather at solving control problems arising in solvers. @AntoinePrv @dchetelat what do you think ?
=> Updated library description

libecole/include/ecole/branching.hpp, libecole/include/ecole/configuring.hpp, libecole/include/ecole/environment/base.hpp, libecole/include/ecole/reward/base.hpp, libecole/include/ecole/reward/isdone.hpp, libecole/src/reward/isdone.cpp, python/src/ecole/wrapper/environment.hpp, python/src/ecole/wrapper/reward.hpp
Minor refactors to improve code readability
=> Improve code clarity

docs/index.rst
Fixed a few typos and partially re-wrote the introduction. What do you think ?
=> Update to the introduction page

.circleci/config.yml, docs/reference/observations.rst, libecole/CMakeLists.txt, libecole/include/ecole/observation/pseudocosts.hpp, libecole/src/observation/pseudocosts.cpp, libecole/src/observation/strongbranchingscores.cpp, libecole/tests/CMakeLists.txt, libecole/tests/src/observation/test-pseudocosts.cpp, python/src/ecole/core/observation.cpp, python/tests/test_observation.py
A new `ObservationFunction` that returns pseudocosts. Analoguous to the current `StrongBranchingScores`
=> Implementation of pseudocost observations.

docs/discussion/theory.rst
=> Doc theory update

README.rst
=> Conda version badges

cmake/Python.cmake
Implement discussion from #133
=> Find Python from PATH with no symlink

docs/contributing.rst, docs/developers/example-observation.rst, docs/index.rst
=> Add example workflow to contribute obs function. Close #148

docs/reference/observations.rst, libecole/include/ecole/observation/khalil-2016.hpp, libecole/include/ecole/observation/nodebipartite.hpp, libecole/src/observation/khalil-2016.cpp, libecole/tests/src/observation/test-khalil-2016.cpp, python/src/ecole/core/observation.cpp, python/tests/test_observation.py
`Khalil2016` now returns a `Khalil2016Obs` struct, with `.features` the data extracted, and `.Features` the enumeration containing the column description.
=> Feature khalil struct

libecole/tests/src/dynamics/test-branching.cpp
=> Minor test bug Close #167

docs/contributing.rst, docs/howto/create-environments.rst, docs/howto/create-functions.rst, docs/howto/instances.rst, docs/howto/observation-functions.rst, docs/howto/reward-functions.rst
I built the docs successfully but was not able to run the `pre-commit` checks, because of some compiler problems on my machine.
=> Fixing a few typos in the doc

README.rst
=> Add related projects to README

libecole/src/observation/nodebipartite.cpp
As noticed by @dchetelat, the rows in `NodeBipartite::row_features` where being overridden when the lp row has both rhs and lhs.
=> Nodebipartite invalid values

dev/run.sh
Make sure the colors are printed when running the `run.sh` script.
=> Bug colors run

libecole/include/ecole/reward/boundintegral.hpp, libecole/src/reward/boundintegral.cpp, python/src/ecole/core/reward.cpp, python/tests/test_reward.py
Fixed issues as @gasse suggested in #202 and resolved #198.  The only issue left to resolve is how we can deal with the naming of the event handlers when there are multiple.  I will open a separate issue so it can be discussed.
=> Integral fix

.github/workflows/continuous-testing.yml, .pre-commit-config.yaml, README.rst, dev/conda.yaml, dev/run.sh, docs/howto/create-environments.rst, docs/howto/create-functions.rst, docs/howto/observation-functions.rst, docs/howto/reward-functions.rst, python/src/ecole/core/instance.cpp, python/tests/_test_instance_old.py, python/tests/test_scip.py
Add black to run on code snippets in documentation during `pre-commit` checks.
=> Blacken docs

dev/run.sh
As suggested by https://stackoverflow.com/a/61551944/5862073
=> Add empty substitution on empty arrays in run.sh

libecole/include/ecole/observation/khalil-2016.hpp, libecole/src/observation/khalil-2016.cpp, libecole/tests/src/observation/test-khalil-2016.cpp, python/src/ecole/core/observation.cpp
The Branching environment has a flag to decide whether to extract pseudo candidates or not: this PR adds the same flag to the Khalil2016 observation.
=> Fix for issue 224

setup.py
=> Add minimum CMake version to setup.py

libecole/include/ecole/scip/model.hpp, libecole/src/scip/model.cpp, libecole/src/scip/scimpl.cpp, python/ecole/src/ecole/core/scip.cpp
=> Add method to reactivate SCIP logger

.github/workflows/continuous-testing.yml, dev/conda.yaml, dev/run.sh
=> Use Python build to build dist

python/ecole/src/ecole/core/dynamics.cpp, python/ecole/src/ecole/core/observation.cpp
Documentation for variables indices usage in obseravtions / action_set.
Only the doc-string were modified.
=> Document indices in obs/action_set

libecole/include/ecole/default.hpp, libecole/include/ecole/dynamics/branching.hpp, libecole/include/ecole/none.hpp, libecole/src/dynamics/branching.cpp, libecole/tests/src/dynamics/test-branching.cpp, python/ecole/src/ecole/__init__.py, python/ecole/src/ecole/core/core.cpp, python/ecole/src/ecole/core/dynamics.cpp, python/ecole/src/ecole/data.py, python/ecole/src/ecole/environment.py, python/ecole/tests/test_data.py, python/ecole/tests/test_dynamics.py
=> Change default type

libecole/include/ecole/instance/combinatorial-auction.hpp, libecole/src/instance/combinatorial-auction.cpp, libecole/src/instance/set-cover.cpp
=> Instance generators difficulty fixes

python/extension-helper/dependencies/public.cmake
=> Update pybind11 to 2.9.1

README.rst, dev/conda.yaml
Add a notice that Ecole is not being actively developed.
=> Maintenance only notice

libecole/src/observation/khalil-2016.cpp
When computing the Khalil2016 features, some rows were considered active while they were not in the LP. Hence their LP index was -1, and the features of the last LP row were extracted for these rows. Luckily sometimes the last row was not itself active, hence the features were depending on the memory state (uninitialized memory), which resulted in non-deterministic features and was catched in #314
=> Bugfix Khalil 2016 observation features
